### ISSUE TITLE
Read config from `_config.yml` when present

### ISSUE THREAD

**Issue by benbalter** [gjtorikian/html-proofer#175]
I taught my Rakefile to read the `html_proofer` property of my `_config.yml` file. 
- [Config](https://github.com/benbalter/benbalter.github.com/blob/master/_config_test.yml)
- [Rakefile](https://github.com/benbalter/benbalter.github.com/blob/master/Rakefile)

Would be awesome to support that automatically, if a `_config.yml` file is present.

**Comment by penibelst** [comment]
What do you think about that?

```yaml
# _proofer.yml
verbose: true
typhoeus:
  ssl_verifyhost: 2
```

```ruby
# Rakefile
HTML::Proofer.new("./_site", :config => '_proofer.yml').run
```

The default for the `config` could be `_proofer.yml`.

**Comment by gjtorikian** [comment]
I do very much like the idea of making this generic as @penibelst suggests. What if it reads from `:config` if provided, or a `:config_key` in a `:config` if that's provided? For example, in addition to the above, it could also be:

``` ruby
HTML::Proofer.new("./_site", :config => '_config.yml', :config_key => 'proofer' ).run
```

``` yaml
# _config.yaml
baseurl: ''
proofer:
 - verbose: true
 - typhoeus:
   ssl_verifyhost: 2
 ```

Not sure if that's overly complicated. I'm not often a fan of introducing a new top-level file in projects (*_proofer.yml*) for people that do not like them.
