### ISSUE TITLE
Error:  wrong number of arguments

### ISSUE THREAD

**Issue by rdricco** [gjtorikian/html-proofer#430]
I'm trying to run html-proofer inside a docker on gitlab and I got this error.

I tried via rake:

```
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./devtest"] on *.html... 


rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/check/links.rb:45:in `block in run'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/node_set.rb:186:in `each'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/check/links.rb:13:in `run'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:103:in `block (2 levels) in check_path'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:100:in `each'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:100:in `block in check_path'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:99:in `each'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:99:in `check_path'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:87:in `block in process_files'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:87:in `map'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:87:in `process_files'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:68:in `check_files'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/html-proofer-3.6.0/lib/html-proofer/runner.rb:40:in `run'
/builds/rdricco/blog/Rakefile:6:in `block in <top (required)>'
/builds/rdricco/blog/vendor/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

And via commandline too:

```
$ htmlproofer --assume-extension ./devtest
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./devtest"] on *.html... 


htmlproofer 3.6.0 | Error:  wrong number of arguments (given 1, expected 0)
```

This is my .gitlab-ci.yml:

```
image: ruby:2.3

cache:
  paths:
    - vendor
  key: "$CI_BUILD_REPO"

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - bundle install --path vendor

test:
  environment: development
  stage: test
  script:
  - rake test
  artifacts:
    paths:
     - devtest
  except:
  - "master"

pages:
  environment: production
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
   paths:
    - public
  only:
  - "master"

````

Any tips on how to proceed?
