### ISSUE TITLE
"internally linking to /, which does not exist" on standard GitHub Pages Jekyll site

### ISSUE THREAD

**Issue by DaveSkender** [gjtorikian/html-proofer#661]
I'm getting a false negative error on a GitHub Actions local build, serve, and test of my [standard GitHub Pages Jekyll site](https://daveskender.github.io/Stock.Indicators/).  

### The error (see [full log](https://github.com/DaveSkender/Stock.Indicators/runs/4291979577?check_suite_focus=true))

```console
- _site/indicators/index.html
*  internally linking to /, which does not exist (line 50)
   <a href="/">
      Stock Indicators
   </a>
```

### From source code

```html
<a href="{{ site.baseurl }}/">
  {{ site.title }}
</a>
```
Note that instances of `{{site.baseurl}}/guide/`, for example, resolve okay; this seems to be limited to root `/`.

### The `html-proofer (3.19.2)` commands (also see [full YAML for job](https://github.com/DaveSkender/Stock.Indicators/blob/9c42cbea1c65fb5abf5b430a80a79ff9d1a459d0/.github/workflows/test.yml)):

```yaml
# GitHub Actions step (after site build and serve on `localhost`)
- name: Test for broken URLs
  working-directory: docs
  run: |
    BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle exec htmlproofer \
      --assume-extension \
      --http-status-ignore "403,999" \
      --url-swap "https\://daveskender.github.io/Stock.Indicators:" \ 
      _site

# `url-swap` to remove hard-coded prod domains (there are none)
```

### Previous recommendation (see #542)

> You'll have to use the `assume-extension` option: https://github.com/gjtorikian/html-proofer#using-with-jekyll

### The workaround

```html
<!-- use absolute URL with full path to root -->
<a href="{{ '/' | absolute_url }}">
  {{ site.title }}
</a>

<!-- builds in local GitHub Actions as: -->
<a href="http://127.0.0.1:4000/">
  Stock Indicators
</a>

<!-- builds in GitHub Pages as: -->
<a href="https://daveskender.github.io/Stock.Indicators/">
  Stock Indicators
</a>
```
