### ISSUE TITLE
QUESTION - `ignore-files` syntax not ignore entire directories as I would expect it to. Is my approach syntax incorrect?

### ISSUE THREAD

**Issue by lwasser** [gjtorikian/html-proofer#775]
Hi Colleagues,
I'm super appreciative of html proofer and use it in many builds. 

I'm struggling with getting ignore-files to work as expected and the documentation and other issues haven't yet helped me. 

i'm trying to ignore two directory paths:
* html/_static
* html/reference/meeting-notes/* (everything in meeting notes including subdirectories)

It's ignoring the _static dir but not the meeting notes. 

[Here is my build: ](https://github.com/pyOpenSci/governance/blob/2b9ddb34c8d74105eea1e51201e6548983b8f61c/.github/workflows/build-docs.yml)

I want the build to ignore both the **static dir** and the **meeting-notes** dir. I've tried many things after reading through other issues including:

* escaping the second dir `\/`, not escaping it, using the full path _build/html and not using it. I am not sure i understand how to correctly tell html proofer to skip over a few different directories in my build. Many thanks for any help. 

```yaml 
uses: chabad360/htmlproofer@master
        with:
          directory: '_build/html'
          arguments: |
           --ignore-files "/html/_static/, /reference\/meeting-notes\/2019/" # do i need to escape this?
```

Failure looks like

```
* At _build/html/reference/meeting-notes/2019/2019-04-04-notes.html:524:

  External link https://www.pyopensci.org/dev_guide/peer_review/peer_review_proc.html#review-timeline failed (status code 404)

* At _build/html/reference/meeting-notes/2019/2019-04-04-notes.html:525:

  External link https://www.pyopensci.org/dev_guide/peer_review/editor_guide.html#editor-checklist failed (status code 404)

```
* [You can see the failure here in my gh action: ](https://github.com/pyOpenSci/governance/actions/runs/3221341663/jobs/5269157840#step:10:28)

Thank you for any guidance!! it's simply not ignoring but i'm not sure what i'm doing wrong. 

Update: i've tried a few other things looking at SO and other sites but it's still not working. 
Currently trying - seeing if some regex could help

```
      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@master
        with:
          directory: '_build/html'
          arguments: |
           --ignore-files "/html/_static/, /.+\/reference\/meeting-notes.+/"
```
